### ISSUE TITLE
There is an exception in IDEA CE 2023.1 + plugin 2023.1.3 java.lang.NullPointerException at com.intellij.idea.plugin.hybris.system.cockpitng.meta.model.CngMetaWidgetExtension

### ISSUE THREAD

**Issue by vito-a** [epam/sap-commerce-intellij-idea-plugin#366] opened 2023-05-01 12:28 UTC
Hi Mykyta,

Thank you for all your efforts for making and supporting this useful plugin.

Please note that there is a following exception when using IDEA 2023.1 + plugin 2023.1.3 :

`java.lang.NullPointerException
	at com.intellij.idea.plugin.hybris.system.cockpitng.meta.model.CngMetaWidgetExtension.<init>(CngMetaWidgetExtension.kt:29)
	at com.intellij.idea.plugin.hybris.system.cockpitng.meta.impl.CngMetaModelProcessorImpl.processWidgets(CngMetaModelProcessorImpl.kt:103)
	at com.intellij.idea.plugin.hybris.system.cockpitng.meta.impl.CngMetaModelAccessImpl$myGlobalMetaModelCache$1$9.invoke(CngMetaModelAccessImpl.kt:92)
	at com.intellij.idea.plugin.hybris.system.cockpitng.meta.impl.CngMetaModelAccessImpl$myGlobalMetaModelCache$1$9.invoke(CngMetaModelAccessImpl.kt:91)
	at com.intellij.idea.plugin.hybris.system.cockpitng.meta.impl.CngMetaModelAccessImpl.createSingleMetaModelCachedValue$lambda$8$lambda$7(CngMetaModelAccessImpl.kt:176)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
	at com.intellij.idea.plugin.hybris.system.cockpitng.meta.impl.CngMetaModelAccessImpl.createSingleMetaModelCachedValue$lambda$8(CngMetaModelAccessImpl.kt:174)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:244)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:244)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:245)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.idea.plugin.hybris.system.cockpitng.meta.impl.CngMetaModelAccessImpl.collectLocalMetaModels(CngMetaModelAccessImpl.kt:114)
	at com.intellij.idea.plugin.hybris.system.cockpitng.meta.impl.CngMetaModelAccessImpl.myGlobalMetaModelCache$lambda$1(CngMetaModelAccessImpl.kt:91)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:244)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:244)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:245)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.idea.plugin.hybris.system.cockpitng.meta.impl.CngMetaModelAccessImpl$getMetaModel$task$1.run$lambda$0(CngMetaModelAccessImpl.kt:138)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:112)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:891)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:149)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:112)
	at com.intellij.idea.plugin.hybris.system.cockpitng.meta.impl.CngMetaModelAccessImpl$getMetaModel$task$1.run(CngMetaModelAccessImpl.kt:131)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

Here is also the screenshot of how it looks in IDEA:
![Screenshot 2023-05-01 141701](https://user-images.githubusercontent.com/9512653/235451386-74465770-94c8-4655-a115-64ebc86ad0e9.png)

Can you please check it when / if you will have some time?

Please inform me if you will need more details regarding this one.

**Comment by mlytvyn** [comment] 2023-05-01 13:40
Hello, @vito-a , thank you for sharing this bug-report, I'll look into it shortly and will try to find out the root cause!

Stay tuned, if fixed it will be available with release `2023.1.5`

**Comment by mlytvyn** [comment] 2023-05-01 13:49
I hoped that `widgetId` will always be present, fixed https://github.com/epam/sap-commerce-intellij-idea-plugin/pull/367.

Please wait for `2023.1.5` release, I'm still polishing new FlexibleSearch 2.0 capabilities

**Comment by mlytvyn** [comment] 2023-05-01 16:29
`2023.1.5` has been scheduled for release, closing issue. If issue will still occur feel free to return :)

**Closed as completed by mlytvyn** 2023-05-01 16:29 UTC
Labels: bug
