### ISSUE TITLE
Duplicate key config error - 2023.2.5

### ISSUE THREAD

**Issue by gomarquette** [epam/sap-commerce-intellij-idea-plugin#536] opened 2023-07-31 15:21 UTC
I'm trying to refresh a 2023.1.6 project in IJ Community Edition 2023.2 with the newest commerce plugin installed (2023.2.5). 

This is the error I get when refreshing the project. It appears the two directories it's claiming are duplicates are the same exact directory?  When I switch back to the older IDE version and older plugin version, everything works fine. 

java.lang.IllegalStateException: Duplicate key config (attempted merging values ConfigModuleDescriptor {name=config, moduleRootDirectory=/Users/brianwaldhart/projects/southwire2105/hybris/config} and ConfigModuleDescriptor {name=config, moduleRootDirectory=/Users/brianwaldhart/projects/southwire2105/hybris/config})
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.intellij.idea.plugin.hybris.project.tasks.ImportProjectProgressModalWindow.run(ImportProjectProgressModalWindow.java:145)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:512)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:87)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mlytvyn** [comment] 2023-07-31 15:37
@gomarquette , oh, quite interesting how it is even possible... Do you have any symlinks or directory junction ?

btw, have you specified `custom config folder` property during the import?

**Comment by gomarquette** [comment] 2023-07-31 15:40
No symlinks in this project and no directory junctions that I'm aware of. like I said - it's weird that it works fine in IJ Community 2023.1.5 w/Commerce plugin 2023.1.6. But when upgrading IJ Community Edition and the plugin, this is the error.

**Comment by mlytvyn** [comment] 2023-07-31 15:44
yeah, that's because of refactored Project Import logic, seems not everything is covered. I'll try to reproduce it.

meanwhile, can you please share project structure and what exact folder you are trying to import.

**Comment by gomarquette** [comment] 2023-07-31 15:45
@mlytvyn - yes, I can share - but since this is a customer project, I'd prefer to share privately if possible. What's the best way to do that?

**Comment by mlytvyn** [comment] 2023-07-31 15:50
@gomarquette , sure, you can drop me a message with details - lytvyn.michael@gmail.com, just do not forget to hide client related details

**Comment by mlytvyn** [comment] 2023-08-01 09:33
@gomarquette , can you please try to remove `.idea` folder and re-import the project? It seems to be incompatibility between legacy and new project import structures.
In meanwhile I'll try to check what can be done to omit such behaviour after upgrade to latest version.

**Comment by gomarquette** [comment] 2023-08-01 13:19
Yes, I can try this once I’m back on my computer on Thu evening. I’ll let
you know how it goes.

**Comment by gomarquette** [comment] 2023-08-05 15:00
Removing the .idea folder and re-importing the project worked!

From: Brian Waldhart ***@***.***>
Date: Tuesday, August 1, 2023 at 8:19 AM
To: epam/sap-commerce-intellij-idea-plugin ***@***.***>
Subject: Re: [epam/sap-commerce-intellij-idea-plugin] Duplicate key config error - 2023.2.5 (Issue #536)
Yes, I can try this once I’m back on my computer on Thu evening. I’ll let you know how it goes.

On Tue, Aug 1, 2023 at 4:33 AM Mykhailo Lytvyn ***@***.******@***.***>> wrote:

@gomarquette<https://github.com/gomarquette> , can you please try to remove .idea folder and re-import the project? It seems to be incompatibility between legacy and new project import structures.
In meanwhile I'll try to check what can be done to omit such behaviour after upgrade to latest version.

**Comment by mlytvyn** [comment] 2023-08-05 19:38
@gomarquette I'm very glad to read that you were able to import your project, I'd like to close this issue as "re-import project" was mentioned in one of the release notes https://github.com/epam/sap-commerce-intellij-idea-plugin/blob/main/CHANGELOG.md#project-import-20.

I'll prepare 3rd https://hybrismart.com article which will describe all changes.

Indeed, there is inconsistency in persistent Project information after version `2023.2`.
Fixing it may be too time-consuming for me, but if someone else is willing to look into it here are few notes:

- Start with `ProjectRefreshAction`
- Check every step implementing new interface `RefreshSupport` and its method `refresh(..)`
- Somewhere there was a mechanism to restore modules selected during initial import which can cause this behaviour.

**Closed as completed by mlytvyn** 2023-08-05 19:38 UTC
